M48
; DRILL file {KiCad 7.0.7} date 2024 February 25, Sunday 13:03:23
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-25T13:03:23-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X34.8Y-77.6
X34.8Y-83.6
T2
X46.99Y-76.2
X48.26Y-27.94
X99.06Y-43.18
X99.06Y-71.12
X123.19Y-27.94
X129.54Y-76.2
T0
M30
